--------------------------------------------------------
--  File created - Thursday-June-24-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence AUTORES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LUIS"."AUTORES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence OBRAS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LUIS"."OBRAS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USUARIOS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LUIS"."USUARIOS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table AUTORES
--------------------------------------------------------

  CREATE TABLE "LUIS"."AUTORES" 
   (	"ID_AUTOR" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"NACIONALIDAD" VARCHAR2(100 BYTE), 
	"SEXO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table AUTORES_OBRAS
--------------------------------------------------------

  CREATE TABLE "LUIS"."AUTORES_OBRAS" 
   (	"ID_OBRA" NUMBER, 
	"ID_AUTOR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EJEMPLARES
--------------------------------------------------------

  CREATE TABLE "LUIS"."EJEMPLARES" 
   (	"ID_EJEMPLAR" NUMBER, 
	"NUMERO_EJEMPLAR" VARCHAR2(100 BYTE), 
	"ESTADO_CONSERVACION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table OBRAS
--------------------------------------------------------

  CREATE TABLE "LUIS"."OBRAS" 
   (	"ID_OBRA" NUMBER, 
	"TITULO" VARCHAR2(100 BYTE), 
	"NACIONALIDAD" VARCHAR2(100 BYTE), 
	"EDITORA" VARCHAR2(100 BYTE), 
	"FECHA_PUBLICACION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRESTAMOS
--------------------------------------------------------

  CREATE TABLE "LUIS"."PRESTAMOS" 
   (	"ID_PRESTAMO" NUMBER, 
	"FECHA_PRESTAMO" DATE, 
	"FECHA_DEVOLUCION" DATE, 
	"ID_USUARIO" NUMBER, 
	"ID_EJEMPLAR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "LUIS"."USUARIOS" 
   (	"ID_USUARIO" NUMBER, 
	"DUI" VARCHAR2(100 BYTE), 
	"NOMBRE" VARCHAR2(200 BYTE), 
	"DIRECCION" VARCHAR2(250 BYTE), 
	"TELEFONO" VARCHAR2(100 BYTE), 
	"AVALADO_POR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into LUIS.AUTORES
SET DEFINE OFF;
Insert into LUIS.AUTORES (ID_AUTOR,NOMBRE,NACIONALIDAD,SEXO) values (1,'test','test','test');
Insert into LUIS.AUTORES (ID_AUTOR,NOMBRE,NACIONALIDAD,SEXO) values (2,'test1234','4354564645645','test');
REM INSERTING into LUIS.AUTORES_OBRAS
SET DEFINE OFF;
REM INSERTING into LUIS.EJEMPLARES
SET DEFINE OFF;
REM INSERTING into LUIS.OBRAS
SET DEFINE OFF;
Insert into LUIS.OBRAS (ID_OBRA,TITULO,NACIONALIDAD,EDITORA,FECHA_PUBLICACION) values (1,'test','test','test',null);
Insert into LUIS.OBRAS (ID_OBRA,TITULO,NACIONALIDAD,EDITORA,FECHA_PUBLICACION) values (2,'test','test','test',null);
Insert into LUIS.OBRAS (ID_OBRA,TITULO,NACIONALIDAD,EDITORA,FECHA_PUBLICACION) values (3,null,null,null,to_date('02-JUN-21','DD-MON-RR'));
Insert into LUIS.OBRAS (ID_OBRA,TITULO,NACIONALIDAD,EDITORA,FECHA_PUBLICACION) values (5,'test','test','test',to_date('02-JUN-21','DD-MON-RR'));
Insert into LUIS.OBRAS (ID_OBRA,TITULO,NACIONALIDAD,EDITORA,FECHA_PUBLICACION) values (6,'test',null,null,to_date('04-JUN-21','DD-MON-RR'));
REM INSERTING into LUIS.PRESTAMOS
SET DEFINE OFF;
REM INSERTING into LUIS.USUARIOS
SET DEFINE OFF;
Insert into LUIS.USUARIOS (ID_USUARIO,DUI,NOMBRE,DIRECCION,TELEFONO,AVALADO_POR) values (1,'123456789','test','test','test',null);
Insert into LUIS.USUARIOS (ID_USUARIO,DUI,NOMBRE,DIRECCION,TELEFONO,AVALADO_POR) values (6,'test','Nombre Temporal',null,'test',null);
Insert into LUIS.USUARIOS (ID_USUARIO,DUI,NOMBRE,DIRECCION,TELEFONO,AVALADO_POR) values (4,null,'Nombre Temporal',null,null,null);
Insert into LUIS.USUARIOS (ID_USUARIO,DUI,NOMBRE,DIRECCION,TELEFONO,AVALADO_POR) values (9,null,'Nombre Temporal',null,null,null);
Insert into LUIS.USUARIOS (ID_USUARIO,DUI,NOMBRE,DIRECCION,TELEFONO,AVALADO_POR) values (10,'13123123123123','test','test','test',null);
--------------------------------------------------------
--  DDL for Index OBRAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LUIS"."OBRAS_PK" ON "LUIS"."OBRAS" ("ID_OBRA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index AUTORES_OBRAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LUIS"."AUTORES_OBRAS_PK" ON "LUIS"."AUTORES_OBRAS" ("ID_OBRA", "ID_AUTOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index AUTORES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LUIS"."AUTORES_PK" ON "LUIS"."AUTORES" ("ID_AUTOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USUARIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LUIS"."USUARIOS_PK" ON "LUIS"."USUARIOS" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRESTAMOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LUIS"."PRESTAMOS_PK" ON "LUIS"."PRESTAMOS" ("ID_PRESTAMO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USUARIOS_UN
--------------------------------------------------------

  CREATE UNIQUE INDEX "LUIS"."USUARIOS_UN" ON "LUIS"."USUARIOS" ("DUI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EJEMPLARES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LUIS"."EJEMPLARES_PK" ON "LUIS"."EJEMPLARES" ("ID_EJEMPLAR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger AUTORES_BI
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "LUIS"."AUTORES_BI" 
  BEFORE INSERT ON autores
  FOR EACH ROW
BEGIN
  SELECT autores_seq.nextval
  INTO :new.id_autor
  FROM dual;
END;
/
ALTER TRIGGER "LUIS"."AUTORES_BI" ENABLE;
--------------------------------------------------------
--  DDL for Trigger OBRAS_BI
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "LUIS"."OBRAS_BI" 
  BEFORE INSERT ON obras
  FOR EACH ROW
BEGIN
  SELECT obras_seq.nextval
  INTO :new.id_obra
  FROM dual;
END;
/
ALTER TRIGGER "LUIS"."OBRAS_BI" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USUARIOS_BI
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "LUIS"."USUARIOS_BI" 
  BEFORE INSERT ON usuarios
  FOR EACH ROW
BEGIN
  SELECT usuarios_seq.nextval
  INTO :new.id_usuario
  FROM dual;
END;
/
ALTER TRIGGER "LUIS"."USUARIOS_BI" ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "LUIS"."USUARIOS" ADD CONSTRAINT "USUARIOS_UN" UNIQUE ("DUI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "LUIS"."USUARIOS" ADD CONSTRAINT "USUARIOS_PK" PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AUTORES_OBRAS
--------------------------------------------------------

  ALTER TABLE "LUIS"."AUTORES_OBRAS" ADD CONSTRAINT "AUTORES_OBRAS_PK" PRIMARY KEY ("ID_OBRA", "ID_AUTOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "LUIS"."AUTORES_OBRAS" MODIFY ("ID_AUTOR" NOT NULL ENABLE);
  ALTER TABLE "LUIS"."AUTORES_OBRAS" MODIFY ("ID_OBRA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OBRAS
--------------------------------------------------------

  ALTER TABLE "LUIS"."OBRAS" ADD CONSTRAINT "OBRAS_PK" PRIMARY KEY ("ID_OBRA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AUTORES
--------------------------------------------------------

  ALTER TABLE "LUIS"."AUTORES" ADD CONSTRAINT "AUTORES_PK" PRIMARY KEY ("ID_AUTOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRESTAMOS
--------------------------------------------------------

  ALTER TABLE "LUIS"."PRESTAMOS" ADD CONSTRAINT "PRESTAMOS_PK" PRIMARY KEY ("ID_PRESTAMO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EJEMPLARES
--------------------------------------------------------

  ALTER TABLE "LUIS"."EJEMPLARES" ADD CONSTRAINT "EJEMPLARES_PK" PRIMARY KEY ("ID_EJEMPLAR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "LUIS"."EJEMPLARES" MODIFY ("ID_EJEMPLAR" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table AUTORES_OBRAS
--------------------------------------------------------

  ALTER TABLE "LUIS"."AUTORES_OBRAS" ADD CONSTRAINT "AUTOR_FK" FOREIGN KEY ("ID_AUTOR")
	  REFERENCES "LUIS"."AUTORES" ("ID_AUTOR") ON DELETE CASCADE ENABLE;
  ALTER TABLE "LUIS"."AUTORES_OBRAS" ADD CONSTRAINT "OBRA_FK" FOREIGN KEY ("ID_OBRA")
	  REFERENCES "LUIS"."OBRAS" ("ID_OBRA") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRESTAMOS
--------------------------------------------------------

  ALTER TABLE "LUIS"."PRESTAMOS" ADD CONSTRAINT "PRESTAMOS_FK1" FOREIGN KEY ("ID_EJEMPLAR")
	  REFERENCES "LUIS"."EJEMPLARES" ("ID_EJEMPLAR") ON DELETE CASCADE ENABLE;
  ALTER TABLE "LUIS"."PRESTAMOS" ADD CONSTRAINT "USUARIO_FK" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "LUIS"."USUARIOS" ("ID_USUARIO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "LUIS"."USUARIOS" ADD CONSTRAINT "USUARIOS_FK1" FOREIGN KEY ("AVALADO_POR")
	  REFERENCES "LUIS"."USUARIOS" ("ID_USUARIO") ON DELETE SET NULL ENABLE;
